project:
  type: website

website:
  title: "Huang's Quarto Pages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "https://huanghe.me/cv/"
        text: CV
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

